### ISSUE TITLE
Persistent errors running tests

### ISSUE THREAD

**Issue by fredericolawson** [makersacademy/problem-solving#129]
On running `rspec` on chapter 4 questions, I get the following response:
```
..tery-quizzes/chapter4/quiz1]$ rspec                                                                                                                           (master✱)

An error occurred while loading ./spec/question_1_spec.rb.
Failure/Error: require "mastery_answer_code_quality"

LoadError:
  cannot load such file -- mastery_answer_code_quality
# ./spec/question_1_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/question_2_spec.rb.
Failure/Error: require "mastery_answer_code_quality"

LoadError:
  cannot load such file -- mastery_answer_code_quality
# ./spec/question_2_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/question_3_spec.rb.
Failure/Error: require "mastery_answer_code_quality"

LoadError:
  cannot load such file -- mastery_answer_code_quality
# ./spec/question_3_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00028 seconds (files took 0.12047 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples
```
I have tried reinstalling Homebrew, RVM & Ruby...

**Comment by LondonJim** [comment]
That's another gem that should have installed when you went through the setup instructions.  Did the gems attached at the root of the mastery quizzes repo install ok?

**Comment by fredericolawson** [comment]
@LondonJim reinstalled and works, thanks!
