### ISSUE TITLE
Ruby Kickstart 1:7

### ISSUE THREAD

**Issue by congcongbo** [makersacademy/problem-solving#68]
The challenge:
```
given a string, return the character after every letter "r"
pirates_say_arrrrrrrrr("are you really learning Ruby?") # => "eenu"
pirates_say_arrrrrrrrr("Katy Perry is on the radio!")   # => "rya"
pirates_say_arrrrrrrrr("Pirates say arrrrrrrrr")        # => "arrrrrrrr"
```
My code:
```
def pirates_say_arrrrrrrrr(string)
  to_return = ""
  i=0
  while i<string.length
    if string[i] == "r" || "R"
      to_return << string[i+1]
    end
    i+=1
  end
    return to_return
end
```

Failures:

```
  1) pirates_say_arrrrrrrrr returns "eeu" when given "are you really learning Ruby?"
     Failure/Error: expect(pirates_say_arrrrrrrrr 'are you really learning Ruby?').to eq 'eenu'
     
     TypeError:
       no implicit conversion of nil into String
     ./session1/challenge/7_string.rb:12:in `pirates_say_arrrrrrrrr'
     ./session1/spec/7.rb:3:in `block (2 levels) in <top (required)>'
```

**Comment by nikeshashar** [comment]
I updated the formatting to make it easier on the eye

**Comment by AlexSusanu** [comment]
@congcongbo try this

def pirates_say_arrrrrrrrr(string)
	to_return = ""

	i = 0

	while i < string.length
		if string[i] == "r" || string[i] == "R"
			to_return << string[i+1].to_s // to string
		end
	i += 1
	end
puts to_return
end

**Comment by ghost** [comment]
@congcongbo try this:

```
def pirates_say_arrrrrrrrr(string)
	to_return = ""

	i = 0
	while i < string.length
		if string[i] == "r" || string[i] == "R"
			to_return << string[i+1].to_s
		end
		i += 1 
	end
to_return
end
```

**Comment by aballal** [comment]
(1) When you are at the last character (at i=length-1) you are still accessing the next character (at i+1) which throws the can't convert nil to string error. Loop only up to length - 1
(2) your if condition's second half needs to be string[i] == "R" as Alex has also pointed out.

**Comment by congcongbo** [comment]
Thank you guys!
